### ISSUE TITLE
UDPNetwork::send problems

### ISSUE THREAD

**Issue by jenglish** [CCSI-CSSI/MuseOpenIG#5]
Found (and fixed) a couple of problems with UDPNetwork::send() while trying to get the CIGI plugin working on Linux.

(1) Specifying anything other than 127.0.0.1 for _host raises an error in bind(); and if you do bind to 127.0.0.1 it only transmits on the loopback interface.  It's usually best to use ip::address_v4::any for bind() calls; but in this case since sender_socket is never read it's not necessary to bind() it at all.

(2) send() used Buffer::getSize() (the buffer capacity) instead of Buffer::getWritten() (the amount of data in the buffer) as the datagram length, which led to trailing garbage in IG-to-host messages.

(3) errors from boost::asio::send_to were ignored.

I've got a fix, will issue a pull request shortly once I figure out how to do so ...

**Comment by crubel** [comment]
We left the bind in, in order to correctly select the correct interface when more that one interface is present in the system.   Code changes were done and tested against a 10.5.63.X network to ensure
you could send UDP data between systems, both broadcast and non-broadcast messages.

Hopefully this will resolve your issues there as well.  Thank you...

**Comment by crubel** [comment]
I should add these fixes will be committed shortly in the 2.0.3 release, should be out shortly...
